apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucg-app
  namespace: bootcamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucg-app
  template:
    metadata:
      labels:
        app: ucg-app
    spec:
      containers:
      - name: ucg
        image: 711387135481.dkr.ecr.us-east-1.amazonaws.com/ucg-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai
              key: OPENAI_API_KEY
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
