apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: nginx-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      
