apiVersion: v1
kind: Pod
metadata:
  name: heavy-pod
spec:
  containers:
  - name: busy
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        memory: "100Gi"
        cpu: "1000"

