apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ucg-hpa
  namespace: bootcamp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ucg-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
