apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  config.txt: |
    Hello from the config!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mount-demo
  namespace: debug-ephemeral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mount
  template:
    metadata:
      labels:
        app: mount
    spec:
      containers:
      - name: tester
        image: busybox
        command: ["/bin/sh", "-c", "cat /config/config.txt && sleep 60"]
        volumeMounts:
          - name: config-vol
            mountPath: /config
      volumes:
      - name: config-vol
        configMap:
          name: example-config

