apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: interns-view-binding
  namespace: interns-ns
subjects:
- kind: Group
  name: interns
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

