apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  good-key: "hello"
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-configmap-ref
spec:
  containers:
    - name: app
      image: alpine:3.20
      command: ["sh", "-c", "cat /config/missing-key && sleep 3600"]
      volumeMounts:
        - name: cfg
          mountPath: /config
  volumes:
    - name: cfg
      configMap:
        name: app-config
        items:
          - key: missing-key
            path: missing-key

