apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80

