apiVersion: v1
kind: Service
metadata:
  name: blue-service
spec:
  type: ClusterIP
  selector:
    version: v1
  ports:
  - port: 80
    targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  type: ClusterIP
  selector:
    app: green
    version: v1
  ports:
  - port: 80
    targetPort: 5678

