apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-scale
  namespace: bootcamp
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:0.49.0
        env:
        - name: TARGET_URL
          value: "http://a29a2ab4e48b745a7926a8333b5f2761-1485839141.us-east-1.elb.amazonaws.com"
        command:
          - /bin/sh
          - -c
          - |
            echo "Running load test against $TARGET_URL"
            k6 run - <<'EOF'
            import http from 'k6/http';
            import { sleep, check } from 'k6';

            export let options = {
              stages: [
                { duration: '1m', target: 5 },
                { duration: '2m', target: 10 },
                { duration: '1m', target: 0 },
              ],
            };

            export default function () {
              const res = http.get(`${__ENV.TARGET_URL}/upload`);
              check(res, { 'status 200': (r) => r.status === 200 });
              sleep(1);
            }
            EOF
