apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-scale
  namespace: bootcamp
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:0.49.0
        command: ["k6", "run", "-"]
        stdin: true
        args:
        - |
          import http from "k6/http";
          import { sleep } from "k6";
          export let options = {
            stages: [
              { duration: "3m", target: 20 },
              { duration: "2m", target: 20 }
            ]
          };
          export default function() {
            http.get("http://{{SERVICE_URL}}/swagger-ui.html");
            sleep(1);
          }

