apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"ucg-app","namespace":"bootcamp"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ucg-app"}},"template":{"metadata":{"labels":{"app":"ucg-app"}},"spec":{"containers":[{"env":[{"name":"OPENAI_API_KEY","valueFrom":{"secretKeyRef":{"key":"OPENAI_API_KEY","name":"openai"}}}],"image":"711387135481.dkr.ecr.us-east-1.amazonaws.com/bootcamp-repo:20251008003109","livenessProbe":{"httpGet":{"path":"/actuator/health","port":8080},"initialDelaySeconds":15},"name":"ucg","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/actuator/health","port":8080},"initialDelaySeconds":5},"resources":{"limits":{"cpu":"250m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2025-10-08T18:30:58Z"
  generation: 15
  name: ucg-app
  namespace: bootcamp
  resourceVersion: "353059"
  uid: 301ee4fd-2844-4e44-9202-63c5334275bc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ucg-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-09T22:36:37-05:00"
      creationTimestamp: null
      labels:
        app: ucg-app
    spec:
      containers:
      - env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_API_KEY
              name: openai
        image: 711387135481.dkr.ecr.us-east-1.amazonaws.com/ucg-app:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: ucg
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-10-08T18:30:59Z"
    lastUpdateTime: "2025-10-08T18:30:59Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-10-10T03:46:38Z"
    lastUpdateTime: "2025-10-10T03:46:38Z"
    message: ReplicaSet "ucg-app-6d8d8777f9" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 15
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
