server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  openai:
    apiKey: ${OPENAI_API_KEY:}
    model: gpt-4o-mini
  csv:
    maxRows: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always
