name: Docker Build & Push - Marco

on:
  push:
    branches:
      - marco
    paths:
      - 'docker/**'
      - 'scripts/**'
      - '.github/workflows/docker_build_and_push.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura Buildx (para soportar multi-arquitectura)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Inicia sesión en GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Construye y publica la imagen multi-arquitectura
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/aquaware-bootcamp/challenge-2025-4:latest

