name: Marco Terraform plan & apply 
on:
  push:
    branches:
      - marco   # 
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN }} 
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd terraform/main && terraform init

      - name: Terraform Plan
        run: cd terraform/main && terraform plan -out=tfplan

      - name: Terraform Apply (only main)
        if: github.ref == 'refs/heads/main'
        run: cd terraform/main && terraform apply -auto-approve tfplan
