name: Test AWS OIDC Connection

on:
  push:
    branches:
      - emir
  workflow_dispatch: # permite ejecutarlo manualmente también

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::711387135481:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Verify AWS identity
        id: verify
        run: |
          echo "Checking AWS identity..."
          aws sts get-caller-identity --output json > identity.json
          cat identity.json

      - name: ✅ Confirm successful OIDC authentication
        run: |
          ACCOUNT_ID=$(jq -r '.Account' identity.json)
          ROLE_ARN=$(jq -r '.Arn' identity.json)

          if
